---
title: "PredictingHappiness"
output: pdf_document
---

## Abstract

We are investigating the World Happiness Index in order to build a model that can predict a country's Happiness Score based on demographic and geographic factors such as literacy levels, cell-phone use, birth rate, death rate, GDP per capita, perceived corruption, etc. We will build an array of linear models, simple and with interaction, and use other regression analysis tools such as Ridge, Lasso, and PCA to understand our data. We will also use regression trees, random forests, and boosted trees to develop prediction methods for our research question. We have determined by running our training data and validated with our test data, that region is an optimal predictor of happiness.  

## Introduction


## The Data

Our final dataset pulls data from a wide variety of sources.  We obtained our “happiness” data from the Gallup World Poll.  Our demographic data on countries came from the US Government.  Data on corruption came from Transparency International.  We combined these disparate sources into one data set with 120 observations and 22 variables.  Each observation refers to a country of the world.  

## Exploratory Data Analysis




## Modeling


## Discussion


## References

e.V, T. I. (n.d.). Corruption Perceptions Index 2017. Retrieved December 4, 2019, from Www.transparency.org website
Lasso, Fernando. “Countries of the World Data (World Factbook US Government).” Erasmus University, 26 Apr. 2018.
“World Happiness Report (Gallup World Poll).” Sustainable Development Solutions Network 

