
```{r}
library(tidyverse)
library(dplyr)
happy_country
```

```{r}
#Eastern Europe Region
eastern_europe <- filter(happy_country, Region == "EASTERN EUROPE")
eastern_europe_nocat <- subset(eastern_europe, select = -c(Region, Country, Climate))
eastern_europe_cor <- eastern_europe_nocat %>%
  cor(eastern_europe_nocat)
```
Top Correlated Varaiables: Perceived Corruption (0.8832017), Net Migration (0.8384467), and Industry(0.8170564).
```{r}
#Linear Model to Predict Eastern European Happiness
EastEurolm <- lm(HappinessScore ~ PercievedCorruptionScore + Netmigration + 
                Industry + Coastlinecoastbyarearatio, data = eastern_europe)
summary(EastEurolm)
```
Adjusted R-squared: 0.9959
p-value: 0.0431

```{r}
#Western Europe Region
western_europe <- filter(happy_country, Region == "WESTERN EUROPE")
western_europe_nocat <- subset(western_europe, select = -c(Region, Country, Climate))
western_europe_cor <- western_europe_nocat %>%
  cor(western_europe_nocat)
```
Top Correlated Variables: Percieved Corruption (0.870394734), GDP per capita (0.854352684), Crops (-0.829523968).
```{r}
#Linear Model to Predict Western European Happiness
WestEurolm <- lm(HappinessScore ~ PercievedCorruptionScore + GDP_percapita + 
                Literacy + Agriculture + Deathrate, data = western_europe)
summary(WestEurolm)
```
Adjusted R-squared: 0.8866
p-value: 2.623e-05

```{r}
#Latin America and Caribean
latin_america_carib <- filter(happy_country, Region == "LATIN AMER. & CARIB")
latin_america_carib_nocat <- subset(latin_america_carib, select = -c(Region, Country, Climate))
latin_america_carib_cor <- latin_america_carib_nocat %>%
  cor(latin_america_carib_nocat)
```


```{r}
happy_country2 <- happy_country
happy_country2$Region[happy_country2$Region == "NORTHERN AFRICA"] <- "AFRICA"
happy_country2$Region[happy_country2$Region == "SUB-SAHARAN AFRICA"] <- "AFRICA"
africa <- filter(happy_country2, Region == "AFRICA")
africa_nocat <- subset(africa, select = -c(Region, Country, Climate))
africa_cor <- africa_nocat %>%
  cor(africa_nocat)
```

```{r}
#Happiness Score sorted by Region
RegionPlot<- ggplot(happy_country, aes(x = Region, y = HappinessScore)) +
 geom_point() +
 labs(x="Region", y="Happiness Score")
RegionPlot
```

```{r}
#Region Linear Model
alymod<- lm(HappinessScore ~ Region, data = happy_country)
summary(alymod)
```
Adjusted R-squared: 0.5754
```{r}
#GDP + Arable Land + Infant Mortality + Percieved Corruption
alymod7 <- lm(HappinessScore ~ GDP_percapita + Arable +     
                Infantmortalityper1000births + PercievedCorruptionScore, 
              data = happy_country)
summary(alymod7)
```
Adjusted R-squared: 0.6734
```{r}
#Region + GDP + Infant Mortality + Percieved Corruption
alymod2 <- lm(HappinessScore ~ Region + GDP_percapita +
                Infantmortalityper1000births + PercievedCorruptionScore,
              data = happy_country)
summary(alymod2)
```
Adjusted R-squared: 0.7558
```{r}
#Region + GDP + Arable Land + Percieved Corruption
alymod3 <- lm(HappinessScore ~ Region + GDP_percapita + Arable + 
                PercievedCorruptionScore, data = happy_country)
summary(alymod3)
```
Adjusted R-squared: 0.7590
```{r}
#Region + GDP + Arable Land + Infant Mortality
alymod4 <- lm(HappinessScore ~ Region + GDP_percapita + Arable + 
                Infantmortalityper1000births, data = happy_country)
summary(alymod4)
```
Adjusted R-squared: 0.7627
```{r}
#Region + GDP + Arable Land + Infant Mortality + Percieved Corruption
alymod5 <- lm(HappinessScore ~ Region + GDP_percapita + Arable + 
              Infantmortalityper1000births + PercievedCorruptionScore, 
              data = happy_country)
summary(alymod5)
```
Adjusted R-squared: 0.7644
```{r}
#Region + GDP + Arable Land + Infant Mortality + Percieved Corruption + Coastline Area
alymod6 <- lm(HappinessScore ~ Region + GDP_percapita + Arable + 
              Infantmortalityper1000births + PercievedCorruptionScore + 
                Coastlinecoastbyarearatio, data = happy_country)
summary(alymod6)
```
Adjusted R-squared: 0.7648 


```{r}
#Normality of Region
ggplot(happy_country, aes(x = Region)) +
geom_histogram(fill = "steelblue", stat="count") +
theme_bw()
```
```{r}
#Normality of GDP per capita
logGDP <- log(happy_country$GDP_percapita)
ggplot(happy_country, aes(x = GDP_percapita)) +
geom_histogram(fill = "steelblue") +
theme_bw()
```
```{r}
#Normality of Arable
logArable <- log(happy_country$Arable)
ggplot(happy_country, aes(x = logArable)) +
geom_histogram(fill = "steelblue", bins = "15") +
theme_bw()
```
```{r}
#Normality of Infantmortalityper1000births
logInfantmortality <- log(happy_country$Infantmortalityper1000births)
ggplot(happy_country, aes(x = logInfantmortality)) +
geom_histogram(fill = "steelblue", bins = "10") +
theme_bw()
```
```{r}
#Normality of PercievedCorruptionScore
logPercievedCorruptionScore <- log(happy_country$PercievedCorruptionScore)
ggplot(happy_country, aes(x = logPercievedCorruptionScore)) +
geom_histogram(fill = "steelblue", bins = "10") +
theme_bw()
```
```{r}
#Normality of Coastlinecoastbyarearatio
logCoastlinecoastbyarearatio <- log(happy_country$Coastlinecoastbyarearatio)
lnCoastlinecoastbyarearatio <- log1p(happy_country$Coastlinecoastbyarearatio)
ggplot(happy_country, aes(x = logCoastlinecoastbyarearatio)) +
geom_histogram(fill = "steelblue", bins = "10") +
theme_bw()
```
```{r}
#Region + GDP + Arable Land + Infant Mortality + Percieved Corruption + Coastline Area
alymod7 <- lm(HappinessScore ~ Region + GDP_percapita + 
                log(Arable) + log(Infantmortalityper1000births) + 
                log(PercievedCorruptionScore) + Coastlinecoastbyarearatio, 
              data = happy_country)
summary(alymod7)
```

```{r}
set.seed(1)
trainS <- sample(1:nrow(happy_country), nrow(happy_country) * .75)
trainD <- happy_country[trainS, ]
testD <- happy_country[-trainS, ]
```

```{r}
#Train 1
linearmodel1 <- lm(HappinessScore ~ Region + GDP_percapita + Arable + 
              Infantmortalityper1000births + PercievedCorruptionScore + 
                Coastlinecoastbyarearatio, data = trainD)
summary(linearmodel1)
```
```{r}
#Test 1
predict(linearmodel1, newdata = testD)
training_MSE <- mean(linearmodel1$residuals^2)
training_MSE
```
```{r}
#Residuals 1
par(mfrow = c(1, 2))
plot(linearmodel1, 1:2)
```

```{r}
#Train 2 with the Log variables
linearmodel2 <- lm(HappinessScore ~ Region + GDP_percapita + 
                log(Arable) + log(Infantmortalityper1000births) + 
                log(PercievedCorruptionScore) + Coastlinecoastbyarearatio, 
                data = trainD)
summary(linearmodel2)
```
```{r}
#Test 2
predict(linearmodel2, newdata = testD)
training_MSE2 <- mean(linearmodel2$residuals^2)
training_MSE2
```
```{r}
#Residuals 2
par(mfrow = c(1, 2))
plot(linearmodel2, 1:2)
```