---
title: "Ridge and Lasso Only Happy"
output: html_document
---

This data comes from a Gallup World Poll asking individuals to rank their life on a scale from 0 to 10 (worst to best life). The happiness index is the HappinessScore and is the average for each country. n = 121 countries, and p = 31 variables (including happiness index).
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
countries_of_the_world
Country_happy<- merge(X2017,countries_of_the_world)
Country_happy2 <- merge(Country_happy, percievedcorruptionwithUS)
happy_country <- Country_happy2 %>%
  na.omit()
library(stringr)
names(happy_country)<-str_replace_all(names(happy_country), c(" " = "." , "," = "" ))
names(happy_country)<-str_replace_all(names(happy_country), c("%" = "", "\\("="", "\\)"="", "\\."="", "\\$"="_", "/"="by"))


happy_country <- subset(happy_country, select = -c(HappinessRank, Whiskerhigh, Whiskerlow, EconomyGDPperCapita, Family, HealthLifeExpectancy, Freedom, Generosity, TrustGovernmentCorruption, DystopiaResidual))


class(happy_country$Phonesper1000)

happy_country<-happy_country%>%
  mutate(Phonesper1000=as.numeric(str_replace_all(Phonesper1000, ",", ".")))
class(happy_country$Phonesper1000)

happy_country<-happy_country%>%
  mutate(PopDensitypersqmi=as.numeric(str_replace_all(PopDensitypersqmi, ",", ".")))
class(happy_country$PopDensitypersqmi)

happy_country<-happy_country%>%
  mutate(Coastlinecoastbyarearatio=as.numeric(str_replace_all(Coastlinecoastbyarearatio, ",", ".")))
class(happy_country$Coastlinecoastbyarearatio)

happy_country<-happy_country%>%
  mutate(Netmigration=as.numeric(str_replace_all(Netmigration, ",", ".")))
class(happy_country$Netmigration)

happy_country<-happy_country%>%
  mutate(Arable=as.numeric(str_replace_all(Arable, ",", ".")))
class(happy_country$Arable)

happy_country<-happy_country%>%
  mutate(Crops=as.numeric(str_replace_all(Crops, ",", ".")))
class(happy_country$Crops)

happy_country<-happy_country%>%
  mutate(Agriculture=as.numeric(str_replace_all(Agriculture, ",", ".")))
class(happy_country$Agriculture)

happy_country<-happy_country%>%
  mutate(Industry=as.numeric(str_replace_all(Industry, ",", ".")))
class(happy_country$Industry)

happy_country<-happy_country%>%
  mutate(Service=as.numeric(str_replace_all(Service, ",", ".")))
class(happy_country$Service)
```

```{r}
num_happy<- happy_country %>%
  select_if(is.numeric)
pairs(num_happy[,1:4], pch = 19)
summary(happy_country)
```

```{r}
xnew <- model.matrix(HappinessScore~., num_happy)[,-1]
ynew <- num_happy$HappinessScore
lambdanew <- 10^seq(10, -2, length = 100)


library(glmnet)

set.seed(489)
trainnew <- sample(1:nrow(xnew), nrow(xnew)/2)
testnew<- (-trainnew)
ytestnew <- ynew[testnew]

#OLS
happylm <- lm(HappinessScore~., data = num_happy)
coef(happylm)

#ridge
happyridge <- glmnet(xnew, ynew, alpha = 0, lambda = lambdanew)
predict(happyridge, s = 0, exact = TRUE, type = 'coefficients')[1:6,]

happylm1 <- lm(HappinessScore~., data = num_happy, subset = train)
happyridge1 <- glmnet(xnew[trainnew,], ynew[trainnew], alpha = 0, lambda = lambdanew)

#find the best lambda from our list via cross-validation
cv.out <- cv.glmnet(xnew[trainnew,], ynew[trainnew], alpha = 0)
bestlamnew <- cv.out$lambda.min
#make predictions
ridge.prednew <- predict(happyridge1, s = bestlamnew, newx = xnew[testnew,])
s.prednew <- predict(happylm1, newdata = num_happy[testnew,])
#check MSE
MSEnew<- mean((s.prednew-ytestnew)^2)
MSEnew
RidgeMSE<- mean((ridge.prednew-ytestnew)^2)
RidgeMSE
#Ridge performs better with this data according to the MSE.

out <- glmnet(xnew[trainnew,],ynew[trainnew],alpha = 0)
ridgepredictnew<-predict(happyridge1, type = "coefficients", s = bestlamnew)[1:6,]
ridgepredictnew

##Lasso

lasso.mod <- glmnet(xnew[trainnew,], ynew[trainnew], alpha = 1, lambda = lambdanew)
lasso.pred <- predict(lasso.mod, s = bestlamnew, newx = xnew[testnew,])
LassoMSE<-mean((lasso.pred-ytestnew)^2)
LassoMSE

lasso.coef  <- predict(lasso.mod, type = 'coefficients', s = bestlamnew)[1:6,]
lasso.coef
```